repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: ^(src|.github)/.*\.ya?ml$
        args:
          - -d
          - relaxed
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
        files: ^(src|.github)/.*\.ya?ml$
